### ISSUE TITLE
Usar print en vez de putStr

### ISSUE THREAD

**Issue by mx-psi** [fdavidcl/publicando-rmarkdown#1]
Haskell incluye una función [`print :: Show a => a -> IO ()`](http://hackage.haskell.org/package/base-4.7.0.2/docs/Prelude.html#v:print) en el _Prelude_ que te puede ser útil. Toma algo [que se pueda mostrar](http://hackage.haskell.org/package/base-4.7.0.2/docs/Text-Show.html) y lo manda a la salida estándar añadiendo un salto de línea.

En tu segundo ejemplo puedes escribir `main = putStr ((show (fact 10)) ++ "\n")` simplemente como `main = print (fact 10)` y en el primero sustituir `putStr` por `print` (y así añades un salto de línea).

**Comment by fdavidcl** [comment]
Muchas gracias @pbaeyens!

_Edit:_ [Release](https://github.com/fdavidcl/publicando-rmarkdown/releases/tag/0.1) actualizada con el nuevo PDF y binario.

**Comment by mx-psi** [comment]
De nada :smiley:!
